const DEFAULT_MENU = [ 
  {
    title: "🥗 Soyuq Qəlyanaltılar",
    items: [
      { name: "Pomidor & xiyar", price: 4, available: true },
      { name: "Göyərti çeşidləri", price: 2, available: true },
      { name: "Süzmə", price: 3, available: true },
      { name: "Zeytun çeşidləri", price: 3, available: true },
      { name: "Turşu çeşidləri", price: 4, available: true },
      { name: "Turşu xiyar", price: 2, available: true },
      { name: "Turşu pomidor", price: 2, available: true },
      { name: "Pendir çeşidləri", price: 5, available: true },
      { name: "Alça", price: 3, available: true },
      { name: "Hövsən soğanı", price: 2, available: true },
      { name: "Qatıq", price: 1, available: true },
      { name: "Acika", price: 2, available: true },
      { name: "Limon", price: 1, available: true },
      { name: "Çaşır", price: 3, available: true },
      { name: "Çörək", price: 1, available: true },
      { name: "Lavaş", price: 1, available: true },
    ],
  },
  {
    title: "🍲 Şorbalar",
    items: [
      { name: "Mərci", price: 3, available: true },
      { name: "Toyuq", price: 3, available: true },
      { name: "Düşbərə", price: 4, available: true },
      { name: "Lobya", price: 3, available: true },
      { name: "Borş", price: 4, available: true },
      { name: "Dovğa", price: 3, available: true },
    ],
  },
  {
    title: "🍔 Street Food / Fast Food",
    items: [
      { name: "Qamburger", price: 5, available: true },
      { name: "Şaurma", price: 5, available: true },
      { name: "Kartof fri", price: 3, available: true },
      { name: "Naggets", price: 3, available: true },
      { name: "Pendir çubuqları", price: 4, available: true },
    ],
  },
  {
    title: "🔥 İsti Qəlyanaltılar",
    items: [
      { name: "Blinçik (ət)", price: 2, available: true },
      { name: "Blinçik (kəsmik)", price: 1, available: true },
      { name: "Çolpa (qrildə / soyutma)", price: 12, available: true },
    ],
  },
  {
    title: "🥙 Salatlar",
    items: [
      { name: "Çoban salatı", price: 3, available: true },
      { name: "Manqal salatı", price: 4, available: true },
      { name: "Mimoza salatı", price: 4, available: true },
      { name: "Pomidor albalı", price: 6, available: true },
      { name: "Paytaxt salatı", price: 4, available: true },
      { name: "Sezar salatı", price: 8, available: true },
      { name: "Vitamin salatı", price: 3, available: true },
      { name: "Yunan salatı", price: 5, available: true },
      { name: "Xırt-xırt badımcan", price: 8, available: true },
    ],
  },
      {
    title: "🍚 Qarnirlər",
    items: [
      { name: "Ev sayağı kartof", price: 3, available: true },
      { name: "Düyü", price: 3, available: true },
      { name: "Qarabaşaq", price: 3, available: true },
    ],
  },
  {
    title: "🐟 Balıq Yeməkləri",
    items: [
      { name: "Forel (qaymaqlı sousda)", price: 0, available: true },
      { name: "Forel setkada (1 kq)", price: 0, available: true },
      { name: "Kütüm tavada (1 kq)", price: 0, available: true },
      { name: "Kefal setkada (1 kq)", price: 0, available: true },
      { name: "Nərə (nar-soğan)", price: 0, available: true },
      { name: "Balıq sırdağı", price: 0, available: true },
      { name: "Ağ balıq (pomidor-soğan)", price: 0, available: true },
      { name: "Ağ balıq (zoğal/zirinc)", price: 0, available: true },
    ],
  },
  {
    title: "🍖 Sac",
    items: [
      { name: "Sac Çolpa", price: 20, available: true },
      { name: "Quzu", price: 30, available: true },
      { name: "Can əti", price: 30, available: true },
      { name: "Qarışıq", price: 35, available: true },
    ],
  },
  {
    title: "🍢 Kabablar",
    items: [
      { name: "Lülə kabab", price: 7, available: true },
      { name: "Tikə kabab", price: 8, available: true },
      { name: "Antrikot", price: 9, available: true },
      { name: "Dana bastırma", price: 9, available: true },
      { name: "Toyuq kabab", price: 5, available: true },
      { name: "Toyuq çöp şiş", price: 3, available: true },
      { name: "Quzu içalat", price: 7, available: true },
      { name: "Xan kabab", price: 7, available: true },
      { name: "Ciyər quyruq", price: 7, available: true },
      { name: "Tərəvəz kabab", price: 1.5, available: true },
      { name: "Kartof quyruq", price: 5, available: true },
      { name: "Kartof lülə", price: 4, available: true },
      { name: "Kartof külləmə", price: 1, available: true },
      { name: "Napoleon kabab", price: 10, available: true },
      { name: "Sarma beyti", price: 10, available: true },
      { name: "Ağ balıq kababı", price: 15, available: true },
      { name: "Nərə balığı kababı", price: 20, available: true },
      { name: "Adana kabab", price: 7, available: true },
      { name: "Urfa kabab", price: 7, available: true },
    ],
  },
  {
    title: "🍛 İsti Yeməklər",
    items: [
      { name: "Yarpaq dolması", price: 7, available: true },
      { name: "Çolpa çığırtma", price: 15, available: true },
      { name: "Çolpa tabaka", price: 15, available: true },
      { name: "Quzu qovurma", price: 8, available: true },
      { name: "Çoban qovurma", price: 8, available: true },
      { name: "Quzu maça", price: 10, available: true },
      { name: "Dana buğlama", price: 8, available: true },
      { name: "Quzu soyutma", price: 8, available: true },
      { name: "Vişnəli can əti", price: 10, available: true },
      { name: "Nar qovurma", price: 8, available: true },
      { name: "Kefli beçə", price: 15, available: true },
      { name: "Spanaqlı toyuq", price: 6, available: true },
      { name: "Qaymaqlı can əti", price: 10, available: true },
      { name: "Qaymaqlı toyuq", price: 6, available: true },
      { name: "Medalyon steyk", price: 15, available: true },
      { name: "Tərəvəzli quzu qabırğa", price: 12, available: true },
      { name: "Toyuq steyk (göbələk sousu)", price: 7, available: true },
    ],
  },
  {
    title: "🥤 İçkilər",
    items: [
      { name: "Kompot", price: 3, available: true },
      { name: "Limonad", price: 3, available: true },
      { name: "Meyvə şirəsi", price: 4, available: true },
      { name: "Qazlı / qazsız su", price: 2, available: true },
      { name: "Cola / Fanta / Sprite", price: 3, available: true },
      { name: "Red Bull", price: 7, available: true },
      { name: "Ayran", price: 2, available: true },
      { name: "Çay", price: 3, available: true },
      { name: "Çay dəstgahı", price: 25, available: true },
    ],
  },
  {
    title: "🍰 Desertlər",
    items: [
      { name: "Mövsümi meyvə", price: 10, available: true },
      { name: "Dondurma", price: 3, available: true },
      { name: "Qarışıq çərəzlər", price: 14, available: true },
      { name: "Mürəbbə", price: 3, available: true },
      { name: "Şokolad", price: 3, available: true },
    ],
  },
  {
    title: "🍺 Pivə Məzələri",
    items: [
      { name: "Qızarmış saçaqlı pendir", price: 4, available: true },
      { name: "Saçaqlı pendir", price: 3, available: true },
      { name: "Qızarmış düşbərə", price: 4, available: true },
      { name: "Göbələk çipsi", price: 4, available: true },
      { name: "Krevetka", price: 4, available: true },
      { name: "Xırt-xırt zeytun", price: 5, available: true },
      { name: "Qızarmış pətənək", price: 4, available: true },
      { name: "Qızarmış boğaz", price: 3, available: true },
      { name: "Grenki", price: 5, available: true },
      { name: "Göbələk julien", price: 6, available: true },
      { name: "Qluşitel", price: 4, available: true },
      { name: "Bildirçin", price: 4, available: true },
      { name: "Çipsi", price: 4, available: true },
      { name: "Tum", price: 3, available: true },
      { name: "Suxari", price: 2, available: true },
      { name: "Noxud", price: 2, available: true },
      { name: "Qızartma noxud", price: 3, available: true },
      { name: "Qovrulmuş püstə", price: 5, available: true },
      { name: "Qovrulmuş fıstıq", price: 3, available: true },
      { name: "Soğan halqası", price: 3, available: true },
      { name: "Kopçonıy forel", price: 0, available: true },
    ],
  },
  {
    title: "🍻 Pivə & İçkilər",
    items: [
      { name: "Xırdalan", price: 0, available: true },
      { name: "Efes", price: 0, available: true },
      { name: "Efes Draft", price: 0, available: true },
      { name: "Efes Zero", price: 0, available: true },
      { name: "Miller", price: 0, available: true },
      { name: "NZS", price: 0, available: true },
    ],
  },
];

